=== Adombom/LEIGxmlAdv/squad.dtd
<!ELEMENT squad (name, email, web?, discord?, picture?, title?, member+)>
<!ATTLIST squad nick CDATA #REQUIRED>
<!ELEMENT member (name, email, remark?)>
<!ATTLIST member id CDATA #REQUIRED nick CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT discord (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT remark (#PCDATA)>

=== Adombom/LEIGxmlAdv/squad.xml
<?xml version="1.0"?>
<!DOCTYPE squad SYSTEM "squad.dtd">
<squad nick="Б!ЭГ">
    <name>League of Extraordinarily Intoxicated Gentlemen</name>
    <email>•CLASSIFIED•</email>
    <web>•CLASSIFIED•</web>
    <discord>https://discord.gg/██████</discord>
    <picture>leigpatch.paa</picture>
    <title>Speshul Activities Center - Ground Branch</title>
    <member id="76561197960749891" nick="bobbab">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561197961266904" nick="Mug Runcher">
        <name>•████ █████</name>
        <email>███████@gmail.com</email>
        <remark>Dodging read receipts since 2002.</remark>
    </member>
    <member id="76561197966888928" nick="SixKiller">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561198004883931" nick="EatPeople">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>Momento Mori</remark>
    </member>
    <member id="76561198015599613" nick="BoavaNet">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561198021527174" nick="Little Ethiopian Kids">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561198023003342" nick="Fisty the Clown">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>It's not "Say no to drugs!" it's "Say no! Two drugs!"</remark>
    </member>
    <member id="76561198044487251" nick="CWrath">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561198064481140" nick="Kano N. Fodder">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561198096719157" nick="YoJimbo">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561197960767818" nick="Sneak69">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561197970766925" nick="hansi">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
    <member id="76561198010391093" nick="shadowhunter388">
        <name>•CLASSIFIED•</name>
        <email>•CLASSIFIED•</email>
        <remark>•CLASSIFIED•</remark>
    </member>
</squad>
